### ISSUE TITLE
sproxy support CONNECT method ?

### ISSUE THREAD

**Issue by ingnelson** [choury/sproxy#10]
Hello.

My name is Nelson, I am from Nicaragua, can you help me with a reverse proxy , i would be glad to pay you for your services.

1) I am behind a firewall

 2) The client is a Android Application, it can sends an HTTP request with the proxy and then to the SSH server to create the tunnel

3) On the internet I found the following:
 HTTP proxy: 50.18.211.227:8043
 Fully qualified domain name (FQDN): 5ef50094901b6f5fccdfd0f6-172-245-22-211.cloudmi.datami.net

The proxy is linked to their domain, the only thing that altered was the domain which removed their IP that it had and put or added mine 172-245-22-211 so that your proxy will not reject the connection.

I show you the connection that WIRESHARK shows me. What you send and what you receive :

![Tunnel1](https://user-images.githubusercontent.com/6626845/86406195-e950cd80-bc6f-11ea-831e-9354405d4ccf.jpg)
![Tunnel2](https://user-images.githubusercontent.com/6626845/86406203-eb1a9100-bc6f-11ea-9db5-0d6d7c572f97.jpg)

It is possible to create a proxy that support CONNECT method and support HTTPS or SSL  like that proxy I found on the internet  ? 

The proxy 50.18.211.227:8043  response is :

HTTP/1.1 200 Connection established.
Server: sdgw

then goes the response from my SSH dropbear and the tunnel is created.

i want a proxy like that on my VPS .

I am going to wait for your reply.

**Comment by choury** [comment]
Sure, sproxy supports CONNECT method, it can acts as reverse  or forward proxy both.
You can also try android version via [google play](https://play.google.com/store/apps/details?id=com.choury.sproxy)

**Comment by ingnelson** [comment]
@choury can you give me the exact commands to install and run sproxy on Ubuntu , please .

**Comment by choury** [comment]
@ingnelson  please refer to [Dockerfile](https://github.com/choury/sproxy/blob/master/Dockerfile)

**Comment by ingnelson** [comment]
@choury  i just download sproxy application on android . I really want to try your project .

on my Ubuntu 16  VPS server  i used this commands : 

```
sudo curl -sS https://get.docker.com/ | sh
gti clone https://github.com/choury/sproxy.git
cd sproxy
```

what is the commnad to run the Dockerfile file ?? 

on the sproxy android app needs : 


```
server or ip
port
shared secret
```

Please i really need to try your project sproxy on my android.

what is the command to run sproxy ? , please please please.

**Comment by choury** [comment]
> @choury i just download sproxy application on android . I really want to try your project .
> 
> on my Ubuntu 16.04 VPS server , i used this commands :
> 
> ```
> sudo curl -sS https://get.docker.com/ | sh
> gti clone https://github.com/choury/sproxy.git
> cd sproxy
> docker build /root/sproxy/
> ```
> 
> I just changed FROM debian to FROM ubuntu:16.04 on the Dockerfile
> 
> what is the commnad to run the Dockerfile file ??
> 
> on the sproxy android app needs :
> 
> ```
> server or ip
> port
> shared secret
> ```
> 
> Please i really need to try your project sproxy on my android.
> 
> what is the command to run sproxy ? , please please please.

Just run `docker run -itd -p {YOURPORT}:80  choury/sproxy`
you will get a proxy port at {YOURPORT}.
`docker run --rm choury/sproxy sproxy --help` to get help usage.

**Comment by ingnelson** [comment]
@choury  the sproxy is running on port 80  ( docker run -itd -p 80:80 choury/sproxy ), but when i use sproxy app on my android , it does not create the tunnel ( it does not open any website . what is it wrong ?  look:

![sproxy](https://user-images.githubusercontent.com/6626845/87328429-b1a91780-c4f2-11ea-9123-bae4b7cbdb04.jpg)


Android

**Comment by choury** [comment]
@ingnelson 
Server Address should be `http://172.245.xx.xxx`.
And there is a policy file in `/sdcard/Android/data/com.choury.sproxy/files/sites.list`, it is prepared for break gfw in China.

It  can be  overridden by two line (which means proxy everything)
```
* proxy
0.0.0.0/0 proxy
```
The policy file can also be edit by setting menu at upper right corner after connected.

**Comment by ingnelson** [comment]
@choury I did what you said , but the app do not create the tunnel . On log says : Connection Refuse 

![Screenshot_2020-07-14-08-42-25-984_com choury sproxy](https://user-images.githubusercontent.com/6626845/87439564-2c833880-c5ae-11ea-8675-6a76196eb7c5.jpg)
![Screenshot_2020-07-14-08-41-59-981_com choury sproxy](https://user-images.githubusercontent.com/6626845/87439578-2ee59280-c5ae-11ea-8c16-be84869eba87.jpg)

What else can we do ?

**Comment by choury** [comment]
@ingnelson The port has not opened or denied by firewall or something?

**Comment by ingnelson** [comment]
@choury the problem it is the sproxy stop or crash on the VPS when I run the sproxy on the Android, then when I log in to my VPS the sproxy is closed or not listening on any port .

I use this command like you said:  `docker run -itd -p 80:80 choury/sproxy`

**Comment by choury** [comment]
> @choury the problem it is the sproxy stop or crash on the VPS when I run the sproxy on the Android, then when I log in to my VPS the sproxy is closed or not listening on any port .
> 
> I use this command like you said: `docker run -itd -p 80:80 choury/sproxy`

Please open a new issue for crash.
