### ISSUE TITLE
IP exposed or sproxy is leaking our IP

### ISSUE THREAD

**Issue by ingnelson** [choury/sproxy#13]
Hello.

I found that sproxy is leaking our ISP IP .
If we connect the sproxy then we visit the website www.whatismyip.com it shows our ISP IP.

Maybe is a DNS leaking problem ??

Look :

![Screenshot_2020-07-19-07-34-48-719_com choury sproxy](https://user-images.githubusercontent.com/6626845/87878912-82881f80-c9a4-11ea-96d7-3fd481cdab14.jpg)
![Screenshot_2020-07-19-07-34-28-072_com sonelli juicessh](https://user-images.githubusercontent.com/6626845/87878924-90d63b80-c9a4-11ea-904d-6f9a62969a9d.jpg)

On the sproxy log (android ) said : 

`[DNS]  ack error:`

I will wait your answer.

**Comment by choury** [comment]
Can you show the strategy  in settings?

**Comment by ingnelson** [comment]
@choury i use the default strategy , all the strategies when the sproxy is installed on the android.

**Comment by choury** [comment]
You should do what I said before:
> There is a policy file in /sdcard/Android/data/com.choury.sproxy/files/sites.list, it is prepared for break gfw in China.
>
>It can be overridden by two line (which means proxy everything)
>```
>* proxy
>0.0.0.0/0 proxy
>The policy file can also be edit by setting menu at upper right corner after connected.

**Comment by ingnelson** [comment]
@choury now it works fine !!.
